### ISSUE TITLE
Can not use "root" compartment for OKE

### ISSUE THREAD

**Issue by xpetoox** [rancher-plugins/kontainer-engine-driver-oke#13]
Hello, I'm not able to use "root" compartment for OKE cluster, because the validation throws an error exception "A valid compartment OCID is required" even thou the OCID is valid (example of beginning of the root compartment OCID: ocid1.tenancy.xxxxxxxxxxxx....). Can you check the validation rules for compartment? Thank you.

Best regards

Peter

**Comment by jlamillan** [comment]
Will do. Thanks for the bug report.

**Comment by jlamillan** [comment]
[Pull request](https://github.com/rancher/ui/pull/4038).

**Comment by jlamillan** [comment]
This issue is resolved. Let us know if you see otherwise.
