### ISSUE TITLE
Cluster driver Oracle OKE download failed

### ISSUE THREAD

**Issue by cpruvost** [rancher-plugins/kontainer-engine-driver-oke#44]
Rancher 2.6.3 Status always dowloading for driver Oracle OKE...In the log look below...(fyi same message with rancher in single node docker on my laptop or rancher in an OKE cluster) 

2022/01/11 12:42:26 [INFO] update kontainerdriver oraclecontainerengine
2022/01/11 12:42:26 [ERROR] Returning previous error: hash does not match, got 0fd2e7407b6ddf39352bf48c70c8c75d9ac1ff5ba64c1c8f9b6a49e6f81e47ca, expected 5a708bfc01c67558adc887258615900082263ca7d6f4160efb1a58501b0cc608
2022/01/11 12:42:26 [ERROR] error syncing 'oraclecontainerengine': handler mgmt-kontainer-driver-lifecycle: hash does not match, got 0fd2e7407b6ddf39352bf48c70c8c75d9ac1ff5ba64c1c8f9b6a49e6f81e47ca, expected 5a708bfc01c67558adc887258615900082263ca7d6f4160efb1a58501b0cc608, requeuing

**Comment by jlamillan** [comment]
Could you confirm you're using the [latest](https://github.com/rancher-plugins/kontainer-engine-driver-oke/releases/tag/v1.7.1) plugin and that the download and checksum are correct:
 
```
https://github.com/rancher-plugins/kontainer-engine-driver-oke/releases/download/v1.7.1/kontainer-engine-driver-oke-linux
0fd2e7407b6ddf39352bf48c70c8c75d9ac1ff5ba64c1c8f9b6a49e6f81e47ca
```

![Image 1-14-22 at 1 17 PM](https://user-images.githubusercontent.com/13613687/149586622-e1edcb05-deee-4499-881b-950583609de8.jpeg)

**Comment by cpruvost** [comment]
It seems..yes..and it is that by defauft after that I installed rancher
Oracle OKE
https://github.com/rancher-plugins/kontainer-engine-driver-oke/releases/download/v1.7.1/kontainer-engine-driver-oke-linux

**Comment by cpruvost** [comment]
So the problem is solved. It seems that in rancher by default the checksum is false, probably a mistake when you deliver the last version of the plugin. Ty for your help...!!!

**Comment by jlamillan** [comment]
Good catch!

We've _restored_ the _original_ intended binary on the v1.7.1 release page that matches the original checksum.

So, you'll likely need to restore the default checksum: `5a708bfc01c67558adc887258615900082263ca7d6f4160efb1a58501b0cc608`

**Comment by cpruvost** [comment]
Now it runs with the other binary version I can delete and reinstall with the new cheksum ?

**Comment by jlamillan** [comment]
I believe the enabled drivers are re-downloaded every time a Rancher pod restarts.

I would try stetting the checksum back to the default (5a708bfc01c67558adc887258615900082263ca7d6f4160efb1a58501b0cc608) then restarting the Deployment / delete the Rancher pods (`kubectl rollout restart deployment rancher`).
