### ISSUE TITLE
The OCI setting screen does not appear.

### ISSUE THREAD

**Issue by ryoryotaro** [rancher-plugins/kontainer-engine-driver-oke#5]
Hello,Thank you for a [great article](https://medium.com/swlh/oke-clusters-from-rancher-2-0-409131ad1293).
I tried to create Oke cluster like you did.
But when   I Click on the OKE icon,Loading icon appeared and this process does not end.
Please tell me what I should  investigate ?
My environment is Rancher v2.3.3 and kontainer-engine-driver-oke v1.0.0.
Regards,

![2019-12-09_11h20_24](https://user-images.githubusercontent.com/16929973/70402660-7c79aa00-1a77-11ea-85ae-068ffce14aee.png)

**Comment by jlamillan** [comment]
Greetings! Most likely, Rancher is not able to load the OKE driver's "custom UI URL" you set when importing the driver. 

Double check the OKE driver settings (tools->drivers->oke driver->edit), including that the URL is correct (https://cdn.jsdelivr.net/gh/rancher-plugins/ui-cluster-driver-oke@v1.0.0/dist/component.js) _and_ that you've whitelisted _both_ `*.github.com` and `*.jsdelivr.net` (note the spelling on delivr).

![edit driver](https://user-images.githubusercontent.com/13613687/70405250-5c9fa300-19f1-11ea-8c08-ab50f29afc08.jpeg)

**Comment by ryoryotaro** [comment]
Thank you for your reply !
I cheked my setting but it seemed to be same on you.

Does the logs appear somewhere ?

![2019-12-09_13h08_28](https://user-images.githubusercontent.com/16929973/70406744-172cb580-1a85-11ea-90c8-b01e5db5e0bd.png)

**Comment by jlamillan** [comment]
I was able to reproduce this using Rancher `v2.3.3`. Thanks for the bug report. 

Firefox's debugger shows the following error while loading  [component.js](https://github.com/rancher-plugins/ui-cluster-driver-oke/blob/master/component/component.js), which appears to prevent the page from loading:
 
```
TypeError: intl.addTranslation is not a function
```

We'll let you know when a fix is ready. Until then, you could try using an earlier version such as `v2.2.6`.

**Comment by jlamillan** [comment]
@ryoryotaro try using the following custom UI URL in the OKE driver, which should resolve your issue:
`https://cdn.jsdelivr.net/gh/rancher-plugins/ui-cluster-driver-oke@v1.0.1-5/dist/component.js`

**Comment by ryoryotaro** [comment]
I tried using custom UI URL you told me.
It’s works fine !
Thank you for your great job !

**Comment by ryoryotaro** [comment]
I tried to crete oke cluster ,I met a error  following
```
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.
Rpc error: code = Unavailable desc = transport is closing
```
Do you have any thoughts about what the cause might be?

**Comment by jlamillan** [comment]
Thanks again for the bug report and your persistence. I've opened a new tracking bug to deal with this issue:  https://github.com/rancher-plugins/kontainer-engine-driver-oke/issues/6
